project_id = "higfoctduijxbszgqhuc"

[functions.product-lookup]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.firecrawl-search]
verify_jwt = false

[functions.firecrawl-product-extract]
verify_jwt = false
